name: CLI

on: 
  push:
    paths:
      - 'cli/**'
  pull_request:
    paths:
      - 'cli/**'

jobs:
  lint:
    name: Lint with Clippy
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy

      - name: Lint with default features
        run: cargo clippy -p civx-cli -- -D warnings

      - name: Lint with all features
        run: cargo clippy -p civx-cli --all-features --all-targets -- -D warnings

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run tests with default features
        run: cargo test -p civx-cli --verbose -- --show-output

      - name: Run tests with all features
        run: cargo test -p civx-cli --all-features --verbose -- --show-output

  build:
    name: Build for all platforms
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]
    env:
        CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build with default features
        run: cargo build -p civx-cli --verbose

      - name: Build with all features
        run: cargo build -p civx-cli --all-features --verbose
